export const ALL_DEPT_REQUEST = "ALL_DEPT_REQUEST";
export const ALL_DEPT_SUCCESS = "ALL_DEPT_SUCCESS";
export const ALL_DEPT_FAIL = "ALL_DEPT_FAIL";

export const CREATE_DEPT_REQUEST = "CREATE_DEPT_REQUEST";
export const CREATE_DEPT_SUCCESS = "CREATE_DEPT_SUCCESS";
export const CREATE_DEPT_FAIL = "CREATE_DEPT_FAIL";

export const UPDATE_DEPT_REQUEST = "UPDATE_DEPT_REQUEST";
export const UPDATE_DEPT_SUCCESS = "UPDATE_DEPT_SUCCESS";
export const UPDATE_DEPT_RESET = "UPDATE_DEPT_RESET";
export const UPDATE_DEPT_FAIL = "UPDATE_DEPT_FAIL";

export const DELETE_DEPT_REQUEST = "DELETE_DEPT_REQUEST";
export const DELETE_DEPT_SUCCESS = "DELETE_DEPT_SUCCESS";
export const DELETE_DEPT_FAIL = "DELETE_DEPT_FAIL";
export const DELETE_DEPT_RESET = "DELETE_DEPT_RESET";

export const CLEAR_ERRORS = "CLEAR_ERRORS";